-- -- Универсальная таблица entities: одна таблица для всех сущностей (table_name + id + data JSON).
-- CREATE TABLE IF NOT EXISTS system.entities (
--     table_name VARCHAR(255) NOT NULL,
--     id VARCHAR(255) NOT NULL,
--     data CLOB,
--     created_at TIMESTAMP,
--     updated_at TIMESTAMP,
--     PRIMARY KEY (table_name, id)
-- );

-- CREATE INDEX IF NOT EXISTS idx_entities_table_name ON system.entities(table_name);
-- CREATE INDEX IF NOT EXISTS idx_entities_table_id ON system.entities(table_name, id);

-- -- Первичные данные: entity_types, actions, ui_bindings в формате JSON (для работы через EntityDTO).
-- INSERT INTO system.entities (table_name, id, data, created_at, updated_at) VALUES
--     ('entity_types', 'Building', '{"name":"Здание","metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('entity_types', 'Contract', '{"name":"Договор","metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('actions', 'order_egrn_extract', '{"name":"Заказать выписку из ЕГРН","description":"Заказывает выписку из ЕГРН для указанного здания","applicableEntityTypes":["Building"],"metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('actions', 'close_contract', '{"name":"Закрыть договор","description":"Закрывает указанный договор","applicableEntityTypes":["Contract"],"metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('actions', 'assign_owner', '{"name":"Назначить владельца","description":"Назначает владельца для указанного здания","applicableEntityTypes":["Building"],"metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('ui_bindings', 'order_egrn_extract', '{"selector":"[data-action=''order_egrn_extract'']","selectorType":"CSS","metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('ui_bindings', 'close_contract', '{"selector":"//button[contains(@class, ''close-contract-btn'')]","selectorType":"XPATH","metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     ('ui_bindings', 'assign_owner', '{"selector":"[data-action=''assign_owner'']","selectorType":"CSS","metadata":{}}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
