package com.zaborstik.platform.core.plan;

import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * План выполнения действия.
 * План - это данные, не код. Хранится в БД, сериализуется, редактируется, генерируется ИИ.
 * <p>
 * Action execution plan.
 * Plan is data, not code. Stored in DB, serialized, edited, generated by AI.
 */
public record Plan(String id, String entityTypeId, String entityId, String actionId, List<PlanStep> steps,
                   PlanStatus status) {
    public enum PlanStatus {
        CREATED,
        EXECUTING,
        COMPLETED,
        FAILED,
        CANCELLED
    }

    public Plan(String entityTypeId, String entityId, String actionId, List<PlanStep> steps) {
        this(UUID.randomUUID().toString(), Objects.requireNonNull(entityTypeId, "EntityType id cannot be null"), Objects.requireNonNull(entityId, "Entity id cannot be null"), Objects.requireNonNull(actionId, "Action id cannot be null"), steps != null ? List.copyOf(steps) : List.of(), PlanStatus.CREATED);
    }

    public Plan(String id, String entityTypeId, String entityId, String actionId,
                List<PlanStep> steps, PlanStatus status) {
        this.id = Objects.requireNonNull(id, "Plan id cannot be null");
        this.entityTypeId = Objects.requireNonNull(entityTypeId, "EntityType id cannot be null");
        this.entityId = Objects.requireNonNull(entityId, "Entity id cannot be null");
        this.actionId = Objects.requireNonNull(actionId, "Action id cannot be null");
        this.steps = steps != null ? List.copyOf(steps) : List.of();
        this.status = Objects.requireNonNull(status, "Status cannot be null");
    }

    public Plan withStatus(PlanStatus newStatus) {
        return new Plan(id, entityTypeId, entityId, actionId, steps, newStatus);
    }

    @Override
    public String toString() {
        return "Plan{id='" + id + "', entityType='" + entityTypeId +
                "', entityId='" + entityId + "', action='" + actionId +
                "', steps=" + steps.size() + ", status=" + status + "}";
    }
}

